sudo: required
language: java
jdk: oraclejdk8

services:
  - postgresql

script:
  - cd CCIS && ./mvnw clean install -DskipTests=false -B 

dist: trusty

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: clinic-center-inf-system